api_version: 1
runtime: python27
threadsafe: yes

handlers:

- url: /
  script: main.app

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: main.app

